### ISSUE TITLE
500 errors for a lot of services

### ISSUE THREAD

**Issue by WToorenburghEasyMarkit** [mlabouardy/komiser#86] opened 2019-05-21 21:25 UTC
Hey there,

I've tried setting up an instance of Komiser, but am getting 500 errors for a lot of services:

* iam/account
* cloudwatch/alarms
* ec2/regions
* resources/regions
* support/open
* support/history

I made sure to create a policy using what is recommended in the readme: https://raw.githubusercontent.com/mlabouardy/komiser/master/policy.json

If I grant all permission to everything, a number of these still fail.

Additionally, the notifications seem to do nothing. I can click on them, and it sends me to `https://<domain>/#`

Example log lines:

```
2019/05/21 14:18:13 Using in-memory cache
127.0.0.1 - - [21/May/2019:14:18:17 -0700] "GET / HTTP/1.0" 200 2856
127.0.0.1 - - [21/May/2019:14:18:17 -0700] "GET /styles.97e9f56065354e4bba5b.bundle.css HTTP/1.0" 200 643
127.0.0.1 - - [21/May/2019:14:18:17 -0700] "GET /inline.31e1fb380eb7cf3d75b1.bundle.js HTTP/1.0" 200 798
127.0.0.1 - - [21/May/2019:14:18:17 -0700] "GET /polyfills.8e93ac3f450806a119ad.bundle.js HTTP/1.0" 200 63719
127.0.0.1 - - [21/May/2019:14:18:17 -0700] "GET /main.2b30d8bea6538f6668bc.bundle.js HTTP/1.0" 200 271491
127.0.0.1 - - [21/May/2019:14:18:17 -0700] "GET /scripts.da8efe539c15fe8a4dea.bundle.js HTTP/1.0" 200 645368
127.0.0.1 - - [21/May/2019:14:18:17 -0700] "GET /vendor.b60046ecc55996eda3e0.bundle.js HTTP/1.0" 200 1789012
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/cloudwatch/alarms HTTP/1.0" 500 48
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/ec2/regions HTTP/1.0" 500 44
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/resources/regions HTTP/1.0" 500 39
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/cloudwatch/alarms HTTP/1.0" 500 48
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/iam/account HTTP/1.0" 500 34
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/iam/users HTTP/1.0" 200 2
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/support/open HTTP/1.0" 500 44
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/support/history HTTP/1.0" 500 44
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/cost/current HTTP/1.0" 200 17
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/cost/history HTTP/1.0" 200 11114
127.0.0.1 - - [21/May/2019:14:18:19 -0700] "GET /aws/cost/forecast HTTP/1.0" 200 19
```

Environment info:
Platform: AWS
Instance type: t3.small
OS: Ubuntu 16.04
Komiser version: 2.1.0
Using in-memory cache
Nginx reverse proxying to localhost:3000 with an SSL cert, version 1.16.0

**Comment by mlabouardy** [comment] 2019-05-21 21:42
@WToorenburghEasyMarkit you need to set AWS_DEFAULT_REGION environment variable

**Comment by WToorenburghEasyMarkit** [comment] 2019-05-21 21:54
Oh, nice! Thank you!

The only strange thing remaining is that there are two errors, saying `iam:GetUser` and `support:DescribeCases` are missing, but those are definitely granted. I set `AWS_DEFAULT_REGION` to `us-west-2`, as that's where I'm doing the majority of my work in AWS. Do those need `AWS_DEFAULT_REGION` to be set to `us-east-1`?

**Comment by mlabouardy** [comment] 2019-05-21 21:56
you can set AWS_DEFAULT_REGION to us-east-1, it wont matter because Komiser will fetch all resources from all regions.

**Comment by mlabouardy** [comment] 2019-05-21 22:00
@WToorenburghEasyMarkit also, Komiser support redis as a caching server, you just need to run it with --redis option and specify expiration time (in minutes):
`komiser start --redis localhost:6379 --duration 30`

**Comment by WToorenburghEasyMarkit** [comment] 2019-05-21 22:21
I changed AWS_DEFAULT_REGION to `us-east-1`, but those two resources are still getting 500 errors :/

Is there a log file I can look at to see why they're failing?

**Comment by mlabouardy** [comment] 2019-05-21 22:21
give me a second, I will try to reproduce it

**Comment by mlabouardy** [comment] 2019-05-21 22:34
I just pushed a fix (https://github.com/mlabouardy/komiser/commit/1a2c22319e449df4c0fd88908a42a872391ce599) it should resolve the issue

**Comment by mlabouardy** [comment] 2019-05-21 22:42
@WToorenburghEasyMarkit let me know, if it fixes the issue

**Comment by WToorenburghEasyMarkit** [comment] 2019-05-21 22:58
Sure! Is there a binary with this fix? I sadly don't have the toolset (or skillset!) for compiling Go applications

**Comment by mlabouardy** [comment] 2019-05-21 22:59
Yes, I just built it, you can either download the Komiser package or use the container image:
`wget https://cli.komiser.io/2.1.0/linux/komiser`

**Comment by WToorenburghEasyMarkit** [comment] 2019-05-21 23:15
Errors still happening with the new binary you linked :(

**Comment by mlabouardy** [comment] 2019-05-21 23:19
can you share with me the logs regarding the error if you dont mind

**Comment by WToorenburghEasyMarkit** [comment] 2019-05-21 23:35
Sure! They're in the issue description. Unless you need the errors as shown in the browser?

**Comment by mlabouardy** [comment] 2019-05-22 08:15
@WToorenburghEasyMarkit  what's the output of https://<domain>/aws/iam/account ?

**Comment by mlabouardy** [comment] 2019-05-22 13:09
I have added some missing permissions to the IAM policy (https://github.com/mlabouardy/komiser/blob/master/policy.json) it might solve your issues

**Closed by mlabouardy** 2019-05-22 13:09 UTC
Labels: bug

**Comment by WToorenburghEasyMarkit** [comment] 2019-05-22 18:01
Hey! Thanks for making those changes.

Sadly, the policy update didn't work. This is the output of `https://<domain>/aws/iam/account`:
`{"error":"iam:GetUser is missing"}`
